module.exports = {
  darkMode: ["class"],
  mode: "jit",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        sm: "540px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
      container: {
        center: true,
        padding: "2rem",
      },
      colors: {
        orange: "#F90",
        horn: "#A1D9F7",
        blue: "#039",
        sky: "#E1F3FF",
        red: "#FB2E13",
        gray: "#999",
        "light-gray": "#F5F3F2",
        "dark-gray": "#1f1f1f",
      },
      fontSize: {
        "4.5xl": "2.875rem",
        "6xl": "4.125rem",
      },
      fontFamily: {
        montserrat: ["var(--montserrat)"],
        seymour: ["var(--seymour)"],
        "pt-root-ui": ["var(--pt-root-ui)"],
      },
      aspectRatio: {
        auto: "auto",
        square: "1 / 1",
        video: "16 / 9",
        "hero-mob": "302/525",
        hero: "921/548",
        "calc-mob": "168/93",
        calc: "220/130",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
        15: "15",
        16: "16",
      },
      lineClamp: {
        7: "7",
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
        15: "15",
      },
      // keyframes: {
      //   "accordion-down": {
      //     from: { height: 0 },
      //     to: { height: "var(--radix-accordion-content-height)" },
      //   },
      //   "accordion-up": {
      //     from: { height: "var(--radix-accordion-content-height)" },
      //     to: { height: 0 },
      //   },
      // },
      // animation: {
      //   "accordion-down": "accordion-down 0.2s ease-out",
      //   "accordion-up": "accordion-up 0.2s ease-out",
      // },
    },
  },

  plugins: ["@tailwindcss/aspect-ratio", "@tailwindcss/line-clamp"],
  variants: {
    aspectRatio: ["responsive", "hover"],
    lineClamp: ["responsive", "hover"],
  },
};
